import logging
import time
from typing import Any, Dict, Optional

import requests
import urllib3

# Suppress SSL warnings for corporate laptop environments
urllib3.disable_warnings(
    urllib3.exceptions.InsecureRequestWarning
)

logger = logging.getLogger(__name__)


class ExecutionAgentError(Exception):
    """Base exception for ExecutionAgent."""


class ExecutionAgent:
    """
    Executes API operations discovered from Swagger/OpenAPI specifications.
    """

    DEFAULT_PATH_PARAMS = {
        "petId": 1,
        "orderId": 1,
        "username": "user1",
    }

    DEFAULT_QUERY_PARAMS = {
        "status": "available",
        "tags": "tag1",
        "username": "user1",
    }

    def __init__(
        self,
        base_url: str,
        timeout: int = 30,
        verify_ssl: bool = False,
    ) -> None:
        """
        Initialize execution agent.

        Args:
            base_url: API base URL.
            timeout: Request timeout in seconds.
            verify_ssl: Whether SSL certificates should be verified.
        """
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.verify_ssl = verify_ssl

    def execute_operation(
        self,
        operation: Dict[str, Any],
        payload: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Execute a single API operation.

        Args:
            operation: Operation metadata from SwaggerParserAgent.
            payload: Optional payload generated by SyntheticDataAgent.

        Returns:
            Execution result dictionary.
        """

        method = str(operation.get("method", "")).upper()
        path = str(operation.get("path", ""))

        try:
            resolved_path = self._resolve_path_parameters(path)

            query_params = self._build_query_parameters(
                operation
            )

            url = f"{self.base_url}{resolved_path}"

            logger.info(
                "Executing %s %s",
                method,
                url,
            )

            start_time = time.perf_counter()

            response = self._send_request(
                method=method,
                url=url,
                payload=payload,
                query_params=query_params,
            )

            elapsed_ms = round(
                (time.perf_counter() - start_time) * 1000,
                2,
            )

            response_body = self._parse_response(response)

            result = {
                "method": method,
                "path": path,
                "url": url,
                "status_code": response.status_code,
                "response_time_ms": elapsed_ms,
                "success": 200 <= response.status_code < 300,
                "response_body": response_body,
                "error": None,
            }

            logger.info(
                "Execution completed: %s %s -> %s",
                method,
                path,
                response.status_code,
            )

            return result

        except Exception as exc:
            logger.exception(
                "Execution failed for %s %s",
                method,
                path,
            )

            return {
                "method": method,
                "path": path,
                "url": None,
                "status_code": None,
                "response_time_ms": None,
                "success": False,
                "response_body": None,
                "error": str(exc),
            }

    def _send_request(
        self,
        method: str,
        url: str,
        payload: Optional[Dict[str, Any]],
        query_params: Optional[Dict[str, Any]] = None,
    ) -> requests.Response:
        """
        Send HTTP request.
        """

        request_kwargs = {
            "timeout": self.timeout,
            "verify": self.verify_ssl,
        }

        if method == "GET":
            return requests.get(
                url,
                params=query_params,
                **request_kwargs,
            )

        if method == "POST":
            return requests.post(
                url,
                json=payload,
                params=query_params,
                **request_kwargs,
            )

        if method == "PUT":
            return requests.put(
                url,
                json=payload,
                params=query_params,
                **request_kwargs,
            )

        if method == "DELETE":
            return requests.delete(
                url,
                params=query_params,
                **request_kwargs,
            )

        raise ExecutionAgentError(
            f"Unsupported HTTP method: {method}"
        )

    def _resolve_path_parameters(
        self,
        path: str,
    ) -> str:
        """
        Replace path parameters with default values.
        """

        resolved = path

        for key, value in self.DEFAULT_PATH_PARAMS.items():
            resolved = resolved.replace(
                f"{{{key}}}",
                str(value),
            )

        return resolved

    def _build_query_parameters(
        self,
        operation: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Build query parameters from Swagger metadata.
        """

        parameters = operation.get(
            "parameters",
            [],
        )

        query_params = {}

        for parameter in parameters:

            if parameter.get("in") != "query":
                continue

            name = parameter.get("name")

            if name in self.DEFAULT_QUERY_PARAMS:
                query_params[name] = (
                    self.DEFAULT_QUERY_PARAMS[name]
                )

        return query_params

    def _parse_response(
        self,
        response: requests.Response,
    ) -> Any:
        """
        Parse response safely.
        """

        try:
            return response.json()
        except Exception:
            return response.text