import logging
import re
import time
from typing import Any, Dict, Optional

import requests
import urllib3

from agents.state_manager_agent import StateManagerAgent

# Suppress SSL warnings for corporate laptop environments
urllib3.disable_warnings(
    urllib3.exceptions.InsecureRequestWarning
)

logger = logging.getLogger(__name__)


class ExecutionAgentError(Exception):
    """Base exception for ExecutionAgent."""


class ExecutionAgent:
    """
    Executes API operations discovered from Swagger/OpenAPI specifications.
    """

    DEFAULT_PATH_PARAMS = {
        "petId": 1,
        "orderId": 1,
        "username": "user1",
    }

    DEFAULT_QUERY_PARAMS = {
        "status": "available",
        "tags": "tag1",
        "username": "user1",
    }

    def __init__(
        self,
        base_url: str,
        timeout: int = 30,
        verify_ssl: bool = False,
        state_manager: Optional[StateManagerAgent] = None,
    ) -> None:
        """
        Initialize execution agent.

        Args:
            base_url: API base URL.
            timeout: Request timeout in seconds.
            verify_ssl: Whether SSL certificates should be verified.
            state_manager: Optional runtime state manager to resolve path parameters.
        """
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.verify_ssl = verify_ssl
        self.state_manager = state_manager

    def execute_operation(
        self,
        operation: Dict[str, Any],
        payload: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Execute a single API operation.

        Args:
            operation: Operation metadata from SwaggerParserAgent.
            payload: Optional payload generated by SyntheticDataAgent.

        Returns:
            Execution result dictionary.
        """

        method = str(operation.get("method", "")).upper()
        path = str(operation.get("path", ""))

        try:
            resolved_path = self._resolve_path_parameters(path)

            query_params = self._build_query_parameters(
                operation
            )

            url = f"{self.base_url}{resolved_path}"

            logger.info(
                "Executing %s %s",
                method,
                url,
            )

            payload = self._resolve_payload_variables(
                payload
            )

            start_time = time.perf_counter()

            response = self._send_request(
                method=method,
                url=url,
                payload=payload,
                query_params=query_params,
            )

            elapsed_ms = round(
                (time.perf_counter() - start_time) * 1000,
                2,
            )

            response_body = self._parse_response(response)

            result = {
                "method": method,
                "path": path,
                "url": url,
                "status_code": response.status_code,
                "response_time_ms": elapsed_ms,
                "success": 200 <= response.status_code < 300,
                "response_body": response_body,
                "error": None,
            }

            logger.info(
                "Execution completed: %s %s -> %s",
                method,
                path,
                response.status_code,
            )

            return result

        except Exception as exc:
            logger.exception(
                "Execution failed for %s %s",
                method,
                path,
            )

            return {
                "method": method,
                "path": path,
                "url": None,
                "status_code": None,
                "response_time_ms": None,
                "success": False,
                "response_body": None,
                "error": str(exc),
            }

    def _send_request(
        self,
        method: str,
        url: str,
        payload: Optional[Dict[str, Any]],
        query_params: Optional[Dict[str, Any]] = None,
    ) -> requests.Response:
        """
        Send HTTP request.
        """

        request_kwargs = {
            "timeout": self.timeout,
            "verify": self.verify_ssl,
        }

        if method == "GET":
            return requests.get(
                url,
                params=query_params,
                **request_kwargs,
            )

        if method == "POST":
            return requests.post(
                url,
                json=payload,
                params=query_params,
                **request_kwargs,
            )

        if method == "PUT":
            return requests.put(
                url,
                json=payload,
                params=query_params,
                **request_kwargs,
            )

        if method == "DELETE":
            return requests.delete(
                url,
                params=query_params,
                **request_kwargs,
            )

        raise ExecutionAgentError(
            f"Unsupported HTTP method: {method}"
        )

    def _resolve_path_parameters(
        self,
        path: str,
    ) -> str:
        """
        Replace path parameters with runtime state values or defaults.
        """

        resolved = path

        for key, default_value in self.DEFAULT_PATH_PARAMS.items():
            placeholder = f"{{{key}}}"

            if placeholder not in resolved:
                continue

            runtime_value = None

            if self.state_manager is not None and self.state_manager.exists(key):
                runtime_value = self.state_manager.get(key)

            if runtime_value is not None:
                resolved_value = str(runtime_value)
                logger.info(
                    "Using runtime value for %s = %s",
                    key,
                    resolved_value,
                )
            else:
                resolved_value = str(default_value)

            resolved = resolved.replace(
                placeholder,
                resolved_value,
            )

        return resolved

    def _build_query_parameters(
        self,
        operation: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Build query parameters from Swagger metadata.
        """

        parameters = operation.get(
            "parameters",
            [],
        )

        query_params = {}

        for parameter in parameters:

            if parameter.get("in") != "query":
                continue

            name = parameter.get("name")

            if name in self.DEFAULT_QUERY_PARAMS:
                query_params[name] = (
                    self.DEFAULT_QUERY_PARAMS[name]
                )

        return query_params

    def _resolve_payload_variables(
        self,
        payload: Optional[Any],
    ) -> Optional[Any]:
        """
        Recursively resolve payload placeholders from runtime state.
        """
        if payload is None:
            return None

        if isinstance(payload, dict):
            return {
                key: self._resolve_payload_variables(
                    value
                )
                for key, value in payload.items()
            }

        if isinstance(payload, list):
            return [
                self._resolve_payload_variables(item)
                for item in payload
            ]

        if isinstance(payload, str):
            return self._resolve_payload_string(payload)

        return payload

    def _resolve_payload_string(
        self,
        value: str,
    ) -> str:
        """
        Resolve individual string placeholders from state.
        """
        if self.state_manager is None:
            return value

        def replace_match(match: re.Match) -> str:
            variable_name = match.group(1)
            if self.state_manager.exists(variable_name):
                resolved_value = self.state_manager.get(
                    variable_name
                )
                logger.info(
                    "Resolved payload variable:%s = %s",
                    variable_name,
                    resolved_value,
                )
                return str(resolved_value)
            return match.group(0)

        return re.sub(
            r"\{\{([^}]+)\}\}",
            replace_match,
            value,
        )

    def _parse_response(
        self,
        response: requests.Response,
    ) -> Any:
        """
        Parse response safely.
        """

        try:
            return response.json()
        except Exception:
            return response.text